name: Auto Build

on:
  push:
    branches: [dev, master, main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/autobuild.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/autobuild.yml'
  workflow_dispatch:

env:
  SDK: '10.0.26100.0'
  PREPARE_PATH: Telegram/build/prepare/prepare.py
  UPLOAD_ARTIFACT: 'true'
  ONLY_CACHE: 'false'

jobs:
  windows:
    name: Windows x64
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories.
        run: |
          mkdir %userprofile%\TBuild\Libraries\win64
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild
          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          echo LibrariesPath=%GITHUB_WORKSPACE%\TBuild\Libraries\win64>>%GITHUB_ENV%

      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: First set up.
        shell: bash
        run: |
          sed -i '/CMAKE_${lang}_FLAGS_DEBUG_INIT/s/${_Zi}//' "$PROGRAMFILES"/CMake/share/cmake*/Modules/Platform/Windows-MSVC.cmake

          echo "$(sha256sum $TBUILD/$REPO_NAME/$PREPARE_PATH | awk '{ print $1 }')" >> CACHE_KEY.txt
          echo "$SDK" >> CACHE_KEY.txt
          echo "CACHE_KEY=$(sha256sum CACHE_KEY.txt | awk '{ print $1 }')" >> $GITHUB_ENV

      - uses: Eden-CI/msvc-dev-cmd@master
        name: Native Tools Command Prompt.
        with:
          arch: x64
          sdk: ${{ env.SDK }}

      - name: NuGet sources.
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: ThirdParty cache.
        uses: actions/cache@v4
        with:
          path: ${{ env.TBUILD }}\ThirdParty
          key: ${{ runner.OS }}-x64-third-party-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-third-party-

      - name: Libraries cache.
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\*
            !${{ env.LibrariesPath }}\cache_keys
            !${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\*
            !${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.OS }}-x64-libs-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-libs-

      - name: Qt cache.
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.OS }}-x64-qt-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-qt-

      - name: Libraries.
        run: |
          %TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat skip-release silent

      - name: Free up some disk space.
        if: env.ONLY_CACHE == 'false'
        shell: bash
        run: find $LibrariesPath '(' '(' ! '(' -name '*.lib' -o -name '*.a' -o -name '*.exe' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' ')' -type f ')' -o -empty ')' -delete

      - name: AyuGram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          cd %TBUILD%\%REPO_NAME%\Telegram

          call configure.bat x64 ^
            -D TDESKTOP_API_TEST=ON ^
            -D CMAKE_CONFIGURATION_TYPES=Debug ^
            -D CMAKE_COMPILE_WARNING_AS_ERROR=ON ^
            -D CMAKE_MSVC_DEBUG_INFORMATION_FORMAT= ^
            -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF ^
            -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF

          cmake --build ..\out --config Debug --parallel

      - name: Check.
        if: env.ONLY_CACHE == 'false'
        shell: bash
        run: |
          filePath="$TBUILD/$REPO_NAME/out/Debug/AyuGram.exe"
          if test -f "$filePath"; then
            echo "Build successfully done."
            ls -lh "$filePath"
          else
            echo "Build error, output file does not exist."
            exit 1
          fi

      - name: Move artifact.
        if: env.UPLOAD_ARTIFACT == 'true' && env.ONLY_CACHE == 'false'
        run: |
          set OUT=%TBUILD%\%REPO_NAME%\out\Debug
          mkdir artifact
          move %OUT%\AyuGram.exe artifact\
          move %OUT%\Updater.exe artifact\

      - uses: actions/upload-artifact@v4
        if: env.UPLOAD_ARTIFACT == 'true' && env.ONLY_CACHE == 'false'
        name: Upload Windows artifact.
        with:
          name: AyuGram Windows x64 Debug
          path: artifact\
